version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: fishhot75012-btcs-node_web_1
      APP_PORT: 8080
  web:
    image: zithiat/bitcoinsilver-node@sha256:69219f4432925ef53e29064ba4c7b4be0e564d5b584be7f91b28389b61c68f22
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - node
  node:
    image: zithiat/bitcoinsilver-node:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/.bitcoinsilver:/root/.bitcoin
    ports:
      - 10567:10567  # RPC
      - 7008:7008    # ZMQ
      - 8334:8334    # P2P

    entrypoint: "bitcoind -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7008 -rpcbind=0.0.0.0 -rpcport=10567 -rpcallowip=0.0.0.0/0 -port=8334 -rpcuser=pooluser -rpcpassword=poolpassword"




